//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.29 at 02:59:00 PM IST 
//


package in.kpmg.iocl.skuapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sku_alt_conversion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sku_alt_conversion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conversion_factor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternate_from_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alternate_to_UOM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="materialCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sku_alt_conversion", propOrder = {
    "conversionFactor",
    "alternateFromUOM",
    "alternateToUOM",
    "materialCode"
})
public class SkuAltConversion {

    @XmlElement(name = "conversion_factor", required = true)
    protected String conversionFactor;
    @XmlElement(name = "alternate_from_UOM", required = true)
    protected String alternateFromUOM;
    @XmlElement(name = "alternate_to_UOM", required = true)
    protected String alternateToUOM;
    @XmlElement(required = true)
    protected String materialCode;

    /**
     * Gets the value of the conversionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversionFactor() {
        return conversionFactor;
    }

    /**
     * Sets the value of the conversionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversionFactor(String value) {
        this.conversionFactor = value;
    }

    /**
     * Gets the value of the alternateFromUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateFromUOM() {
        return alternateFromUOM;
    }

    /**
     * Sets the value of the alternateFromUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateFromUOM(String value) {
        this.alternateFromUOM = value;
    }

    /**
     * Gets the value of the alternateToUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateToUOM() {
        return alternateToUOM;
    }

    /**
     * Sets the value of the alternateToUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateToUOM(String value) {
        this.alternateToUOM = value;
    }

    /**
     * Gets the value of the materialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * Sets the value of the materialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialCode(String value) {
        this.materialCode = value;
    }

}
